=== jwayne/mol455/idea-2.5.1/wf/dtds/commandSet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Susan Fields (The Institute for Genomic Research) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="annotation">
		<xs:annotation>
			<xs:documentation>Command Set Schema to be used in the workflow system.
			Copyright 2002, The Institute for Genomic Research (TIGR).
			All rights reserved.
            		</xs:documentation>
		</xs:annotation>
	</xs:element>
	<!-- Command Status Type, stores the command status information -->
	<xs:complexType name="commandStatusType">
		<xs:sequence>
			<xs:element name="returnValue" type="xs:integer" minOccurs="0"/>
			<xs:element name="message" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<!-- Param Type, keeps the information for a parameter for any command or config element -->
	<xs:complexType name="paramType">
		<xs:sequence>
			<xs:element name="key" type="xs:string"/>
			<xs:element name="value" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<!-- Config Type, keeps the configuration information for a command set -->
	<xs:complexType name="configType">
		<xs:sequence>
			<xs:element name="filePath" type="xs:string"/>
			<xs:element name="param" type="paramType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- Status Type, keeps the status information for a command or command set -->
	<xs:complexType name="commandSetStatusType">
		<xs:sequence>
			<xs:element name="total" type="xs:integer"/>
			<xs:element name="complete" type="xs:integer"/>
			<xs:element name="incomplete" type="xs:integer"/>
			<xs:element name="failed" type="xs:integer"/>
			<xs:element name="errors" type="xs:integer"/>
			<xs:element name="running" type="xs:integer"/>
			<xs:element name="pending" type="xs:integer"/>
			<xs:element name="waiting" type="xs:integer"/>
			<xs:element name="interrupted" type="xs:integer"/>
			<xs:element name="message" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<!--Valid list of states for commands and command sets-->
	<xs:simpleType name="listOfStatesType" final="restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="incomplete"/>
			<xs:enumeration value="pending"/>
			<xs:enumeration value="successful"/>
			<xs:enumeration value="running"/>
			<xs:enumeration value="waiting"/>
			<xs:enumeration value="completed"/>
			<xs:enumeration value="errors"/>
			<xs:enumeration value="interrupted"/>
			<xs:enumeration value="failed"/>
		</xs:restriction>
	</xs:simpleType>
	<!--Command Type, models a single simple command object-->
	<xs:complexType name="commandType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="comment" type="xs:string"/>
			<xs:element name="id" type="xs:long" minOccurs="0"/>
			<xs:element name="configMapId" type="xs:long" minOccurs="0"/>
			<xs:element name="startTime" type="xs:dateTime"/>
			<xs:element name="endTime" type="xs:dateTime"/>
			<xs:element name="state" type="listOfStatesType"/>
			<xs:element name="waitUntil" type="xs:dateTime"/>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="retryCount" type="xs:integer" minOccurs="0"/>
			<xs:element name="timeOut" type="xs:integer" minOccurs="0"/>
			<xs:element name="status" type="commandStatusType" minOccurs="0"/>
			<xs:element name="param" type="paramType" minOccurs="0"/>
			<xs:element name="flag" type="xs:string" minOccurs="0"/>
			<xs:element name="arg" type="xs:string" minOccurs="0"/>
			<xs:element name="dceSpecification" type="dceSpecification"/>
		</xs:sequence>
	</xs:complexType>
	<!--Command Set Type, models a command set object-->
	<xs:complexType name="commandSetType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="comment" type="xs:string"/>
			<xs:element name="id" type="xs:long" minOccurs="0"/>
			<xs:element name="configMapId" type="xs:long" minOccurs="0"/>
			<xs:element name="fileName" type="xs:string"/>
			<xs:element name="parentFileName" type="xs:string"/>
			<xs:element name="startTime" type="xs:dateTime"/>
			<xs:element name="endTime" type="xs:dateTime"/>
			<xs:element name="state" type="listOfStatesType"/>
			<xs:element name="waitUntil" type="xs:dateTime"/>
			<xs:element name="config" type="configType"/>
			<xs:element name="status" type="commandSetStatusType"/>
			<xs:group ref="commandList" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="version" type="xs:string"/>
	</xs:complexType>
	<!--Command List Group, contains one or more commands and command sets-->
	<xs:group name="commandList">
		<xs:choice>
			<xs:element name="command" type="commandType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="commandSet" type="commandSetType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:group>
	<xs:complexType name="commandSetRootType">
		<xs:sequence>
			<xs:element name="commandSet" type="commandSetType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="commandSetRoot" type="commandSetRootType"/>
	<xs:complexType name="dceSpecification">
		<xs:sequence>
			<xs:element name="jobID" type="xs:string"/>
			<xs:element name="executionHost" type="xs:string"/>
			<xs:element name="log" type="xs:string"/>
			<xs:element name="specFile" type="xs:string"/>
			<xs:element name="group" type="xs:string"/>
			<xs:element name="mail" type="xs:string"/>
			<xs:element name="os" type="xs:string"/>
			<xs:element name="memory" type="xs:string"/>
			<xs:element name="queue" type="xs:string"/>
			<xs:element name="hosts" type="xs:string"/>
			<xs:element name="duration" type="xs:string"/>
			<xs:element name="priority" type="xs:string"/>
			<xs:element name="passthrough" type="xs:string"/>
			<xs:element name="workingDir" type="xs:string"/>
			<xs:element name="reqStartTime" type="xs:dateTime"/>
			<xs:element name="execEnv" type="execEnvironment"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="optional" default="condor"/>
	</xs:complexType>
	<xs:complexType name="execEnvironment">
		<xs:sequence>
			<xs:element name="envFile" type="xs:string"/>
			<xs:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== jwayne/mol455/idea-2.5.1/wf/examples/set_iterator_with_config_template.xml
<?xml version="1.0" encoding="UTF-8"?>
    
<commandSetRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation='commandSet.xsd'>
    <commandSet type="serial">
        <name>My Iterative Flow</name>
        <configMapId>1</configMapId>
        <commandSet type="parallel">
            <configMapId>1.1</configMapId>
            <name>MySubflow</name>
            <config>
                <param>
                    <key>template</key>
                    <value>subworkflow_template.xml</value>
                </param>
            </config>
        </commandSet>
    </commandSet> <!-- End top level command set -->
</commandSetRoot> <!-- End of root -->

=== jwayne/mol455/idea-2.5.1/wf/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowInstanceBuilder/all_vs_all_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<commandSetRoot type="template" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation='commandSet.xsd'>
    <commandSet type="serial">
        <name>all_vs_all</name>
        <configMapId>1</configMapId>
        <commandSet type ="parallel">
            <name>get_sequence</name>
            <configMapId>2</configMapId>
            <command>
                <name>RunUnixCommand</name>
                <configMapId>2.1</configMapId>
            </command>
            <command>
                <name>RunUnixCommand</name>
                <configMapId>2.2</configMapId>
            </command>
            <command>
                <name>RunUnixCommand</name>
                <configMapId>2.3</configMapId>
            </command>
            <command>
                <name>RunUnixCommand</name>
                <configMapId>2.4</configMapId>
            </command>
          <restarted>false</restarted>
        </commandSet>
        <command>    
            <name>RunUnixCommand</name>
            <configMapId>1.1</configMapId>
        </command>
        <command>    
            <name>RunUnixCommand</name>
            <configMapId>1.2</configMapId>
        </command>
      <restarted>false</restarted>
    </commandSet>
    <host>aegan-lx</host>
<port>-1</port>
</commandSetRoot>

=== jwayne/mol455/idea-2.5.1/wf/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowInstanceBuilder/set_with_config_in_config_template.xml
<?xml version="1.0" encoding="UTF-8"?>
    
<commandSetRoot type="template" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation='commandSet.xsd'>
    <commandSet type="serial">
        <name>Template with Config</name>
        <configMapId>1</configMapId>
        <commandSet type="parallel">
            <configMapId>1.1</configMapId>
            <name>MySubflow</name>
            <config>
                <param>
                    <key>template</key>
                    <value>template.xml</value>
                </param>
                <param>
                    <key>configfile</key>
                    <value>config.ini</value>
                </param>
            </config>
          <restarted>false</restarted>
        </commandSet>
      <restarted>false</restarted>
    </commandSet> <!-- End top level command set -->
</commandSetRoot> <!-- End of root -->

=== jwayne/mol455/idea-2.5.1/idea_gene_template_user_tree.xml
<?xml version="1.0" encoding="UTF-8"?>
    
<commandSetRoot type="template" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation='commandSet.xsd'>
  <commandSet type="distributed-serial" version="3.1.1">
    <name>IDEA-gene</name>
    <configMapId>1</configMapId>
    <command>
      <name>run-paml</name>
      <configMapId>1.2</configMapId>
      <type>RunUnixCommand</type>
      <param>
	<key>command</key>
	<value><IDEA_BASE_DIR>/idea-B-run-paml.pl</value>
      </param>
      <dceSpec type="&lt;GRID_TYPE&gt;">
	<duration>medium</duration>
	<priority>medium</priority>
      </dceSpec>
    </command>
    <command>
      <name>merge-runs</name>
      <configMapId>1.3</configMapId>
      <type>RunUnixCommand</type>
      <param>
	<key>command</key>
	<value><IDEA_BASE_DIR>/idea-C-merge-runs.pl</value>
      </param>
      <dceSpec type="&lt;GRID_TYPE&gt;">
	<duration>medium</duration>
	<priority>medium</priority>
	<queue>fast</queue>
      </dceSpec>
    </command>
    <command>
      <name>parse-output</name>
      <configMapId>1.4</configMapId>
      <type>RunUnixCommand</type>
      <param>
	<key>command</key>
	<value><IDEA_BASE_DIR>/idea-D-parse-output.pl</value>
      </param>
      <dceSpec type="&lt;GRID_TYPE&gt;">
	<duration>medium</duration>
	<priority>medium</priority>
	<queue>fast</queue>
      </dceSpec>
    </command>
    <dceSpec type="&lt;GRID_TYPE&gt;">
      <duration>medium</duration>
      <priority>medium</priority>
      <queue>fast</queue>
    </dceSpec>
  </commandSet> <!-- End top level command set -->
</commandSetRoot> <!-- End of root -->

=== jwayne/mol455/idea-2.5.1/wf/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowInstanceBuilder/workflow_with_params_template.xml
<?xml version="1.0" encoding="UTF-8"?>
    
<commandSetRoot type="template" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation='commandSet.xsd'>
	<commandSet type="serial">
		<name>SerialSingleWorkflow</name>
		<configMapId>1</configMapId>
        <config>
            <param>
                <key>second</key>
                <value>second_value</value>
            </param>
        </config>
		<command>
			<name>CheckUpdates</name>
			<configMapId>1.1</configMapId>
            <param>
                <key>command</key>
                <value>ls</value>
            </param>
		</command> <!-- End of command CheckUpdates-->
		<command>
			<name>WriteSequence</name>
			<configMapId>1.2</configMapId>
            <flag>l</flag>
            <arg>*.ini</arg>
		</command> <!-- End of WriteSequence -->
		<command>
			<name>VerifySequence</name>
			<configMapId>1.3</configMapId>
            <param>
                <key>command</key>
                <value>ls</value>
            </param>
            <param>
                <key>user</key>
                <value>amahurka</value>
            </param>
		</command> <!-- End of command VerifySequence-->
	  <restarted>false</restarted>
	</commandSet> <!-- End top level command set -->
</commandSetRoot> <!-- End of root -->

=== jwayne/mol455/idea-2.5.1/idea_local_gene_template_user_tree.xml
<?xml version="1.0" encoding="UTF-8"?>
    
<commandSetRoot type="template" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation='commandSet.xsd'>
  <commandSet type="serial" version="3.1.1">
    <name>IDEA-gene</name>
    <configMapId>1</configMapId>
    <command>
      <name>run-paml</name>
      <configMapId>1.2</configMapId>
      <type>RunUnixCommand</type>
      <param>
	<key>command</key>
	<value><IDEA_BASE_DIR>/idea-B-run-paml.pl</value>
      </param>
    </command>
    <command>
      <name>merge-runs</name>
      <configMapId>1.3</configMapId>
      <type>RunUnixCommand</type>
      <param>
	<key>command</key>
	<value><IDEA_BASE_DIR>/idea-C-merge-runs.pl</value>
      </param>
    </command>
    <command>
      <name>parse-output</name>
      <configMapId>1.4</configMapId>
      <type>RunUnixCommand</type>
      <param>
	<key>command</key>
	<value><IDEA_BASE_DIR>/idea-D-parse-output.pl</value>
      </param>
    </command>
  </commandSet> <!-- End top level command set -->
</commandSetRoot> <!-- End of root -->

=== jwayne/mol455/idea-2.5.1/wf/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowInstanceBuilder/iterator_template.xml
<?xml version="1.0" encoding="UTF-8"?>
    
<commandSetRoot type="template" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation='commandSet.xsd'>
    <commandSet type="serial">
        <name>Unix Command Flow</name>
        <configMapId>1</configMapId>
        <command>
            <name>RunUnixCommand</name>
            <configMapId>1.1</configMapId>
        </command> <!-- End of command check updates -->
        <commandSet type="parallel">
            <configMapId>1.2</configMapId>
            <name>Sub Workflow</name>
            <command>
                <name>RunUnixCommand</name>
                <configMapId>1.2.1</configMapId>
            </command> <!-- End of command check updates -->
            <command>
                <name>RunUnixCommand</name>
                <configMapId>1.2.2</configMapId>
            </command> <!-- End of command check updates -->
          <restarted>false</restarted>
        </commandSet>
      <restarted>false</restarted>
    </commandSet> <!-- End top level command set -->
</commandSetRoot> <!-- End of root -->

=== jwayne/mol455/idea-2.5.1/wf/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowModifier/restart_template.xml
<?xml version="1.0" encoding="UTF-8"?>
    
<commandSetRoot type="template" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation='commandSet.xsd'>
  <commandSet type="serial" version="3.0">
    <name>command-set-A</name>
    <configMapId>0</configMapId>
    <commandSet type="parallel" version="3.0">
      <name>command-set-B</name>
      <configMapId>1</configMapId>
      <commandSet type="serial" version="3.0">
	<name>command-set-D</name>
	<configMapId>1.1</configMapId>
	<commandSet type="parallel" version="3.0">
	  <name>command-set-F</name>
	  <configMapId>1.1.1</configMapId>
	  <commandSet type="serial" version="3.0">
	    <name>command-set-I</name>
	    <configMapId>1.1.1.1</configMapId>
	    <command>
	      <name>command-I1</name>
	      <configMapId>1.1.1.1.1</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>distributed-command-I2</name>
	      <configMapId>1.1.1.1.2</configMapId>
	      <dceSpec type="&lt;GRID_TYPE&gt;">
		<duration>medium</duration>
		<priority>low</priority>
		<OS>Linux</OS>
		<queue>Assembly</queue>
	      </dceSpec>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>command-I3</name>
	      <configMapId>1.1.1.1.3</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="parallel" version="3.0">
	    <name>command-set-J</name>
	    <configMapId>1.1.1.2</configMapId>
	    <command>
	      <name>command-J1</name>
	      <configMapId>1.1.1.2.1</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>distributed-command-J2</name>
	      <configMapId>1.1.1.2.2</configMapId>
	      <dceSpec type="&lt;GRID_TYPE&gt;">
		<duration>medium</duration>
		<priority>low</priority>
		<OS>Linux</OS>
		<queue>Assembly</queue>
	      </dceSpec>
	      <type>RunUnixCommand</type>
	    </command>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="distributed-serial" version="3.0">
	    <name>command-set-K</name>
	    <configMapId>1.1.1.3</configMapId>
	    <command>
	      <name>command-K1</name>
	      <configMapId>1.1.1.3.1</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>distributed-command-K2</name>
	      <configMapId>1.1.1.3.2</configMapId>
	      <dceSpec type="&lt;GRID_TYPE&gt;">
		<duration>medium</duration>
		<priority>low</priority>
		<OS>Linux</OS>
		<queue>Assembly</queue>
	      </dceSpec>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>command-K3</name>
	      <configMapId>1.1.1.3.3</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="distributed-parallel" version="3.0">
	    <name>command-set-L</name>
	    <configMapId>1.1.1.4</configMapId>
	    <command>
	      <name>distributed-command-L1</name>
	      <configMapId>1.1.1.4.1</configMapId>
	      <dceSpec type="&lt;GRID_TYPE&gt;">
		<duration>medium</duration>
		<priority>low</priority>
		<OS>Linux</OS>
		<queue>Assembly</queue>
	      </dceSpec>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>command-L2</name>
	      <configMapId>1.1.1.4.2</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="remote-serial" version="3.0">
	    <name>placeholder-command-set-M</name>
	    <configMapId>1.1.1.5</configMapId>
            <fileName>/home/aegan/bin/projects/workflow-2005-11-15/workflow/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowModifier/restart-subfile-M.xml</fileName>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="remote-parallel" version="3.0">
	    <name>placeholder-command-set-N</name>
	    <configMapId>1.1.1.6</configMapId>
            <fileName>/home/aegan/bin/projects/workflow-2005-11-15/workflow/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowModifier/restart-subfile-N.xml</fileName>
	    <restarted>false</restarted>
	  </commandSet>
	  <restarted>false</restarted>
	</commandSet>
	<commandSet type="serial" version="3.0">
	  <name>command-set-G</name>
	  <configMapId>1.1.2</configMapId>
	  <command>
	    <name>command-O</name>
	    <configMapId>1.1.2.1</configMapId>
	    <type>RunUnixCommand</type>
	  </command>
	  <commandSet type="serial" version="3.0">
	    <name>command-set-P</name>
	    <configMapId>1.1.2.2</configMapId>
	    <command>
	      <name>command-P1</name>
	      <configMapId>1.1.2.2.1</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>distributed-command-P2</name>
	      <configMapId>1.1.2.2.2</configMapId>
	      <dceSpec type="&lt;GRID_TYPE&gt;">
		<duration>medium</duration>
		<priority>low</priority>
		<OS>Linux</OS>
		<queue>Assembly</queue>
	      </dceSpec>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>command-P3</name>
	      <configMapId>1.1.2.2.3</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="parallel" version="3.0">
	    <name>command-set-Q</name>
	    <configMapId>1.1.2.3</configMapId>
	    <command>
	      <name>distributed-command-Q1</name>
	      <configMapId>1.1.2.3.1</configMapId>
	      <dceSpec type="&lt;GRID_TYPE&gt;">
		<duration>medium</duration>
		<priority>low</priority>
		<OS>Linux</OS>
		<queue>Assembly</queue>
	      </dceSpec>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>command-Q2</name>
	      <configMapId>1.1.2.3.2</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="distributed-serial" version="3.0">
	    <name>command-set-R</name>
	    <configMapId>1.1.2.4</configMapId>
	    <command>
	      <name>command-R1</name>
	      <configMapId>1.1.2.4.1</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>distributed-command-R2</name>
	      <configMapId>1.1.2.4.2</configMapId>
	      <dceSpec type="&lt;GRID_TYPE&gt;">
		<duration>medium</duration>
		<priority>low</priority>
		<OS>Linux</OS>
		<queue>Assembly</queue>
	      </dceSpec>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>command-R3</name>
	      <configMapId>1.1.2.4.3</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="distributed-parallel" version="3.0">
	    <name>command-set-S</name>
	    <configMapId>1.1.2.5</configMapId>
	    <command>
	      <name>command-S1</name>
	      <configMapId>1.1.2.5.1</configMapId>
	      <type>RunUnixCommand</type>
	    </command>
	    <command>
	      <name>distributed-command-S2</name>
	      <configMapId>1.1.2.5.2</configMapId>
	      <dceSpec type="&lt;GRID_TYPE&gt;">
		<duration>medium</duration>
		<priority>low</priority>
		<OS>Linux</OS>
		<queue>Assembly</queue>
	      </dceSpec>
	      <type>RunUnixCommand</type>
	    </command>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="remote-serial" version="3.0">
	    <name>placeholder-command-set-T</name>
	    <configMapId>1.1.2.6</configMapId>
            <fileName>/home/aegan/bin/projects/workflow-2005-11-15/workflow/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowModifier/restart-subfile-T.xml</fileName>
	    <restarted>false</restarted>
	  </commandSet>
	  <commandSet type="remote-parallel" version="3.0">
	    <name>placeholder-command-set-U</name>
	    <configMapId>1.1.2.7</configMapId>
            <fileName>/home/aegan/bin/projects/workflow-2005-11-15/workflow/testing/testprops/UnitTest/org/tigr/workflow/common/WorkflowModifier/restart-subfile-U.xml</fileName>
	    <restarted>false</restarted>
	  </commandSet>
	  <command>
	    <name>distributed-command-V</name>
	    <configMapId>1.1.2.8</configMapId>
	    <dceSpec type="&lt;GRID_TYPE&gt;">
	      <duration>medium</duration>
	      <priority>low</priority>
	      <OS>Linux</OS>
	      <queue>Assembly</queue>
	    </dceSpec>
	    <type>RunUnixCommand</type>
	  </command>
	  <restarted>false</restarted>
	</commandSet>
	<commandSet type="parallel" version="3.0">
	  <name>command-set-H</name>
	  <configMapId>1.1.3</configMapId>
	  <command>
	    <name>distributed-command-W</name>
	    <configMapId>1.1.3.1</configMapId>
	    <dceSpec type="&lt;GRID_TYPE&gt;">
	      <duration>medium</duration>
	      <priority>low</priority>
	      <OS>Linux</OS>
	      <queue>Assembly</queue>
	    </dceSpec>
	    <type>RunUnixCommand</type>
	  </command>
	  <command>
	    <name>command-X</name>
	    <configMapId>1.1.3.2</configMapId>
	    <type>RunUnixCommand</type>
	  </command>
	  <restarted>false</restarted>
	</commandSet>
        <restarted>false</restarted>
      </commandSet>
      <command>
	<name>distributed-command-E</name>
	<configMapId>1.2</configMapId>
	<dceSpec type="&lt;GRID_TYPE&gt;">
	  <duration>medium</duration>
	  <priority>low</priority>
	  <OS>Linux</OS>
	  <queue>Assembly</queue>
	</dceSpec>
	<type>RunUnixCommand</type>
      </command>
      <restarted>false</restarted>
    </commandSet>
    <command>
      <name>command-C-wait</name>
      <configMapId>2</configMapId>
      <type>RunUnixCommand</type>
    </command>
    <restarted>false</restarted>
  </commandSet> <!-- End top level command set -->
</commandSetRoot> <!-- End of root -->
